# Generated by Django 3.2.12 on 2022-08-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='business_books',
            new_name='Ksb_books',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='fiction_books',
            new_name='engineering_books',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='recommended_books',
            new_name='hesa_books',
        ),
    ]
